import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { PDFDocument, PDFName } from 'pdf-lib';
import { createBuildPlanV1 } from '../../utils/buildPlan';
import { dismissStartupAnnouncement } from './startupHarness';
import { APP_PATH, drawMark, installedArtwork, saveFile } from './paintingHarness';

test('a single painted figure moves, saves and prints without a character rig', async ({ page, browser, baseURL }, info) => {
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto(APP_PATH); await dismissStartupAnnouncement(page);
  await page.getByTestId('getting-started-dialog').getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByTestId('workflow-stage-character').click();
  await page.getByTestId('character-draw-object').click();
  await page.getByRole('textbox', { name: 'Object name', exact: true }).fill('Orbit');
  await page.getByTestId('paint-workspace').getByRole('button', { name: 'Change shape', exact: true }).click();
  await page.getByTestId('shape-editor').getByRole('button', { name: 'Ellipse', exact: true }).click();
  await page.getByTestId('use-shape').click();
  await page.getByRole('button', { name: 'Filled ellipse', exact: true }).click();
  await page.getByRole('button', { name: 'Paint color #2389da', exact: true }).click();
  await drawMark(page, [{ x: -36, y: -36 }, { x: 36, y: 36 }]);
  await page.getByRole('button', { name: 'Brush', exact: true }).click();
  await page.getByRole('button', { name: 'Thin brush', exact: true }).click();
  await page.getByRole('button', { name: 'Paint color #172033', exact: true }).click();
  await drawMark(page, [{ x: -10, y: 10 }]);
  await drawMark(page, [{ x: 10, y: 10 }]);
  await page.getByRole('button', { name: 'Line', exact: true }).click();
  await drawMark(page, [{ x: -12, y: -10 }, { x: 12, y: -10 }]);
  await page.getByTestId('paint-workspace').getByRole('button', { name: 'Add object', exact: true }).click();
  const added = await saveFile(page, info, 'orbit-added');
  const id = added.project.selectedSceneObjectId!;
  const revision = added.project.sceneObjects[id].artwork!.revision;
  expect(added.project.partOrder).toEqual([]);
  expect(added.project.skeleton).toBeNull();
  expect(added.project.mechanisms).toEqual([]);
  await page.getByRole('button', { name: 'Delete object', exact: true }).click();
  await expect(page.getByTestId(`scene-object-item-${id}`)).toHaveCount(0);
  await page.keyboard.press('ControlOrMeta+z');
  await expect(page.getByTestId(`scene-object-item-${id}`)).toBeVisible();
  expect((await saveFile(page, info, 'orbit-delete-undone')).project).toEqual(added.project);

  await page.getByTestId('workflow-stage-path').click();
  await expect(page.locator('.editor-stage-frame[data-stage="path"]')).toBeVisible();
  await page.getByTestId('novice-path-panel').getByRole('button', { name: 'Add path', exact: true }).click();
  await page.getByLabel('New path target').selectOption(`scene-object:${id}`);
  await page.getByTestId('add-path-chooser').getByRole('button', { name: 'Create path', exact: true }).click();
  await page.getByRole('button', { name: 'Draw free path', exact: true }).click();
  const box = (await page.getByTestId('path-three-puppet-canvas').boundingBox())!;
  await page.mouse.move(box.x + box.width * .4, box.y + box.height * .6); await page.mouse.down();
  await page.mouse.move(box.x + box.width * .5, box.y + box.height * .4, { steps: 4 });
  await page.mouse.move(box.x + box.width * .6, box.y + box.height * .6, { steps: 4 }); await page.mouse.up();
  const position = async () => JSON.parse(await page.getByTestId('path-three-puppet-state')
    .getAttribute('data-three-scene-object-screen-targets') || '[]').find((target: { id: string }) => target.id === id);
  await expect.poll(position).toBeDefined();
  const rest = await position();
  await page.getByRole('button', { name: 'Play paths', exact: true }).click();
  await expect.poll(position).not.toEqual(rest);
  await page.getByRole('button', { name: 'Pause all paths', exact: true }).click();
  await installedArtwork(page, id, revision);
  const moving = await saveFile(page, info, 'orbit-moving');
  expect(moving.project.partOrder).toEqual([]);
  expect(Object.values(moving.project.paths)).toHaveLength(1);
  const plan = createBuildPlanV1(moving.project);
  expect(plan.parts.map(part => part.kind)).toEqual(['object']);
  expect(plan.steps.map(step => step.phase)).toEqual(['cut-object', 'place-object']);
  expect(plan.steps.every(step => step.pinIds.length === 0 && step.stack.length === 0)).toBe(true);
  await page.getByTestId('workflow-stage-project').click();
  await installedArtwork(page, id, revision);
  await page.getByTestId('workflow-stage-assembly').click();
  await installedArtwork(page, id, revision);
  await expect(page.getByText('Character pins', { exact: true })).toHaveCount(0);
  await expect(page.getByText('Character fasteners', { exact: true })).toHaveCount(0);
  await expect(page.getByTestId('assembly-mode-switch').getByRole('button', { name: 'Objects', exact: true })).toBeVisible();
  await expect(page.getByTestId('assembly-active-board-coords')).toHaveCount(0);
  await page.screenshot({ path: info.outputPath('orbit-assembly.png') });
  await page.getByTestId('workflow-stage-blueprint').click();
  const pending = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Build PDF', exact: true }).click();
  const pdfFile = info.outputPath('orbit-build.pdf'); await (await pending).saveAs(pdfFile);
  const pdf = await PDFDocument.load(await readFile(pdfFile));
  expect(pdf.getPageCount()).toBe(2);
  expect(pdf.getPages()[0].node.Resources()?.has(PDFName.of('XObject'))).toBe(true);

  const clean = await browser.newContext({ baseURL, viewport: { width: 1366, height: 768 }, acceptDownloads: true });
  try {
    const next = await clean.newPage(); await next.goto(APP_PATH); await dismissStartupAnnouncement(next);
    const picker = next.waitForEvent('filechooser');
    await next.getByTestId('getting-started-dialog').getByRole('button', { name: 'Open Project', exact: true }).click();
    await (await picker).setFiles(moving.file);
    await expect(next.getByTestId('status-bar')).toContainText('Loaded project');
    await next.getByTestId('workflow-stage-character').click();
    await next.getByTestId('character-draw-paint').click();
    await drawMark(next, [{ x: -10, y: -20 }, { x: 10, y: -20 }]);
    const continued = await saveFile(next, info, 'orbit-continued');
    expect(continued.project.partOrder).toEqual([]);
    expect(continued.project.skeleton).toBeNull();
    expect(continued.project.mechanisms).toEqual([]);
    expect(continued.project.paths).toEqual(moving.project.paths);
    expect(continued.project.sceneObjects[id].artwork!.operations).toHaveLength(5);
  } finally { await clean.close(); }
});
