#!/usr/bin/env bun
import { readFileSync } from 'node:fs';
import { existsSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve } from 'node:path';

type GeneratorAdapter = {
  id: string;
  sourceSsot: string;
  description: string;
  mode: 'board' | 'non-board' | 'all';
  run: (outputDir: string) => void;
};

type AdapterResult = {
  adapter_id: string;
  source_ssot: string;
  output_dir: string;
  status: 'ok' | 'skipped';
  error?: string;
};

type GenerationSummary = {
  generated_at: string;
  output_dir: string;
  requested_adapters: string[];
  executed: AdapterResult[];
  board_final: {
    path: string;
    has_generated_by_marker: boolean;
  };
  manifest_changed: boolean;
  managed_file_count: number | null;
  added_managed_files?: string[];
  removed_managed_files?: string[];
};

const GENERATORS: readonly GeneratorAdapter[] = [
  {
    id: 'python-non-board-fabrication',
    sourceSsot: 'fabrication/generate_fabrication_templates.py',
    description: 'Legacy non-board assets from the Python generator snapshot bundle.',
    mode: 'non-board',
    run: (outputDir) => {
      execFileSync('python3', ['fabrication/generate_fabrication_templates.py', '--output', outputDir], {
        stdio: 'pipe'
      });
    }
  },
  {
    id: 'ts-board-fabrication',
    sourceSsot: 'scripts/generate-fabrication-board.ts',
    description: 'Board map now generated by TypeScript so board geometry stays in-repo and type-checkable.',
    mode: 'board',
    run: (outputDir) => {
      execFileSync('bun', ['scripts/generate-fabrication-board.ts', '--output', outputDir], {
        stdio: 'pipe'
      });
    }
  }
] as const;
const GENERATOR_IDS = new Set(GENERATORS.map((generator) => generator.id));

const parseArgs = () => {
  const args = process.argv.slice(2);
  const options: {
    output: string;
    adapters: string[];
    onlyBoard: boolean;
    onlyNonBoard: boolean;
    compareCommitted: boolean;
  } = {
    output: resolve(process.cwd(), 'fabrication'),
    adapters: [],
    onlyBoard: false,
    onlyNonBoard: false,
    compareCommitted: false
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    switch (arg) {
      case '--output': {
        const value = args[index + 1];
        if (!value) throw new Error('Missing value for --output');
        options.output = resolve(process.cwd(), value);
        index += 1;
        break;
      }
      case '--adapters': {
        const value = args[index + 1];
        if (!value) throw new Error('Missing value for --adapters');
        options.adapters = value.split(',').map(item => item.trim()).filter(Boolean);
        for (const adapterId of options.adapters) {
          if (!GENERATOR_IDS.has(adapterId)) {
            throw new Error(`Unknown adapter id ${adapterId}`);
          }
        }
        index += 1;
        break;
      }
      case '--only-board':
        options.onlyBoard = true;
        break;
      case '--only-non-board':
        options.onlyNonBoard = true;
        break;
      case '--compare-committed':
        options.compareCommitted = true;
        break;
      case '--help':
      case '-h':
        printUsage();
        process.exit(0);
      default:
        if (arg.startsWith('--')) throw new Error(`Unknown flag ${arg}`);
        printUsage();
        throw new Error(`Unknown positional argument ${arg}`);
    }
  }

  if (options.onlyBoard && options.onlyNonBoard) {
    throw new Error('--only-board and --only-non-board cannot both be set');
  }

  if (!options.adapters.length) {
    options.adapters = GENERATORS.map(generator => generator.id);
  }

  return options;
};

const printUsage = () => {
  console.log(`Usage: bun scripts/generate-fabrication-assets.ts [--output <dir>] [--adapters id1,id2] [--only-board] [--only-non-board] [--compare-committed]\n`);
  console.log('Available adapters:');
  for (const generator of GENERATORS) {
    console.log(`  ${generator.id}\n    source: ${generator.sourceSsot}\n    mode: ${generator.mode}\n    ${generator.description}`);
  }
};

const loadManifest = (outputDir: string) => {
  const manifestPath = join(outputDir, 'manifest.json');
  if (!existsSync(manifestPath)) return null;
  try {
    return JSON.parse(readFileSync(manifestPath, 'utf8')) as Record<string, unknown>;
  } catch {
    return null;
  }
};

const ensureDirectory = (output: string) => {
  if (!existsSync(output)) mkdirSync(output, { recursive: true });
};

const validateBoardContract = (output: string) => {
  const boardPath = join(output, 'board-final.svg');
  if (!existsSync(boardPath)) {
    return 'missing board-final.svg in generated output';
  }
  const boardText = readFileSync(boardPath, 'utf8');
  const rootTag = boardText.match(/<svg\b[^>]*>/)?.[0];
  if (!rootTag) return 'generated board has no root svg tag';
  if (!/data-generated-by=\"scripts\/generate-fabrication-board\.ts\"/.test(rootTag)) {
    return 'board-final.svg missing data-generated-by= scripts/generate-fabrication-board.ts marker';
  }
  return null;
};

const maybeCompareCommittedBoard = (outputDir: string) => {
  const committed = join(process.cwd(), 'fabrication', 'board-final.svg');
  if (!existsSync(committed)) return 'missing committed fabrication/board-final.svg';
  const committedText = readFileSync(committed, 'utf8');
  const generatedText = readFileSync(join(outputDir, 'board-final.svg'), 'utf8');
  return committedText === generatedText ? null : 'generated board-final.svg does not match committed artifact in output directory';
};

const run = () => {
  const options = parseArgs();
  const outputDir = options.output;
  ensureDirectory(outputDir);

  const beforeManifest = loadManifest(outputDir);
  const manifestBefore = beforeManifest ? beforeManifest.managed_files : null;

  const requested = new Set(options.adapters);
  const selected = new Set<string>();
  for (const generator of GENERATORS) {
    if (!requested.has(generator.id)) continue;
    if (options.onlyBoard && generator.mode !== 'board') continue;
    if (options.onlyNonBoard && generator.mode !== 'non-board') continue;
    selected.add(generator.id);
  }

  const requestBoardAdapter = [...selected].some((adapterId) => {
    const match = GENERATORS.find((generator) => generator.id === adapterId);
    return match?.mode === 'board';
  });
  let boardGenerated = false;
  const results: AdapterResult[] = [];

  const runOrder = [...GENERATORS].sort((left, right) => {
    const leftPriority = left.mode === 'non-board' ? 0 : 1;
    const rightPriority = right.mode === 'non-board' ? 0 : 1;
    return leftPriority - rightPriority || left.id.localeCompare(right.id);
  });

  for (const generator of runOrder) {
    const shouldRun = selected.has(generator.id);
    if (!shouldRun) {
      if (requested.has(generator.id)) {
        results.push({ adapter_id: generator.id, source_ssot: generator.sourceSsot, output_dir: outputDir, status: 'skipped' });
      }
      continue;
    }

    try {
      generator.run(outputDir);
      if (generator.mode === 'board') boardGenerated = true;
      results.push({ adapter_id: generator.id, source_ssot: generator.sourceSsot, output_dir: outputDir, status: 'ok' });
    } catch (error) {
      const message = error instanceof Error ? error.message : `${error}`;
      results.push({
        adapter_id: generator.id,
        source_ssot: generator.sourceSsot,
        output_dir: outputDir,
        status: 'skipped',
        error: message
      });
      if (generator.mode === 'non-board') {
        process.stderr.write(`Unable to run ${generator.id}: ${message}\n`);
      } else {
        throw error;
      }
    }
  }

  const shouldValidateBoard = (requestBoardAdapter || options.onlyBoard) && !options.onlyNonBoard;
  if (shouldValidateBoard) {
    if (!boardGenerated) {
      throw new Error('Board adapter was requested but did not execute');
    }
    const boardValidationError = validateBoardContract(outputDir);
    if (boardValidationError) {
      throw new Error(boardValidationError);
    }
  }

  const afterManifest = loadManifest(outputDir);
  const manifestChanged = JSON.stringify(beforeManifest) !== JSON.stringify(afterManifest);
  const boardCompared = options.compareCommitted ? maybeCompareCommittedBoard(outputDir) : null;
  if (options.compareCommitted && boardCompared) {
    throw new Error(boardCompared);
  }

  const summary: GenerationSummary = {
    generated_at: new Date().toISOString(),
    output_dir: outputDir,
    requested_adapters: Array.from(selected),
    executed: results,
    board_final: {
      path: 'board-final.svg',
      has_generated_by_marker: true
    },
    manifest_changed: manifestChanged,
    managed_file_count: afterManifest && Array.isArray(afterManifest.managed_files) ? afterManifest.managed_files.length : null
  };

  if (afterManifest && Array.isArray(manifestBefore) && Array.isArray(afterManifest.managed_files)) {
    const beforeSet = new Set(manifestBefore);
    const afterSet = new Set(afterManifest.managed_files);
    const added = [...afterSet].filter(entry => !beforeSet.has(entry));
    const removed = [...beforeSet].filter(entry => !afterSet.has(entry));
    summary.added_managed_files = added;
    summary.removed_managed_files = removed;
  }

  process.stdout.write(`${JSON.stringify(summary)}\n`);
};

run();
